FROM ubuntu

RUN apt-get update && \
  apt-get install python-pip -y && \
  apt-get install libmysqlclient-dev -y && \
  apt-get install git -y && \
  pip install flask && \
  pip install flask-mysql && \
  pip install gunicorn && \
  git clone https://github.com/neilpeterson/flask-voting-app.git /opt/vote-app

WORKDIR /opt/vote-app
ENTRYPOINT ["python"]
CMD ["main.py"]