FROM ubuntu

RUN apt-get update && \
  apt-get install nginx -y && \
  apt-get install python-pip -y && \
  apt-get install libmysqlclient-dev -y && \
  apt-get install supervisor -y && \
  apt-get install git -y && \
  pip install flask && \
  pip install flask-mysql && \
  pip install gunicorn && \
  git clone https://github.com/neilpeterson/flask-voting-app.git /opt/vote-app && \
  cp /opt/vote-app/deployment/default /etc/nginx/sites-available/ && \
  cp /opt/vote-app/deployment/supervisor-config.conf /etc/supervisor/conf.d/

ENTRYPOINT ["/opt/vote-app/deployment/azure-docker-swarm/vote-entrypoint.sh"]
